#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --remove \
        sddm-ubuntu-theme \
        /usr/share/sddm/themes/win10
fi

# Tag to allow some debhelper commands to inject relevant code

runByUsers () {
	# $1 is default folder of user
	# $2 is name of user
	cd $1
    runuser -l $2 -c "rm -rf $1/.face.icon"
}

# Get Names of users
cat /etc/passwd | grep '/home/' | grep -v 'cups\|syslog\|mysql\|mongodb' | \
cut -d':' -f1 > /tmp/homes.list

while read USUARIO; do
	runByUsers "/home/$USUARIO" "$USUARIO"
 	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
 	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
 	fi
done < /tmp/homes.list
runByUsers "/etc/skel" "root"
